// Hypsometric altitude color bands for filament changes. Pure, DOM-free: the
// export readout, the 3MF embed, and the preview all consume these.

// [r,g,b] 0..1, one per band (ascending altitude).
export const BAND_COLORS = [
  [0.16, 0.36, 0.55], // 0 blue   — water  (≤ sea level)
  [0.28, 0.48, 0.28], // 1 green  — forest (≤ treeline)
  [0.60, 0.62, 0.38], // 2 tundra — alpine meadow/krummholz (≤ tundra line)
  [0.55, 0.55, 0.55], // 3 grey   — rock   (≤ snowline)
  [0.96, 0.96, 0.96], // 4 white  — snow   (> snowline)
];

const TUNDRA_M = 400; // alpine-tundra band width above the treeline (metres)

// φ = |center latitude|. Plateau-then-linear: plateaus near the equator/subtropics,
// declines poleward. Approximate & tunable; ignores the subtropical treeline hump.
export function bandThresholds(centerLat) {
  const p = Math.abs(centerLat);
  const clamp = (v, hi) => Math.max(0, Math.min(hi, v));
  const treeline = clamp((3800 * (70 - p)) / 40, 3800); // plateau ≤30°, 0 at ≥70°
  const snowline = clamp((5000 * (75 - p)) / 45, 5000); // plateau ≤30°, 0 at ≥75°
  const tundra = Math.min(treeline + TUNDRA_M, snowline);
  return [0, treeline, tundra, snowline]; // ascending; ties collapse (colorChanges)
}

// value → band index 0..4. Generic over metres OR print-Z (same comparison).
// Threshold is the TOP of the lower band (strict >): value 0 is water, 0+ε green.
export function bandOf(value, thresholds) {
  let b = 0;
  for (const t of thresholds) if (value > t) b++;
  return b;
}

// Band of the base plate / first-loaded filament. A threshold at or below the
// lowest printed elevation cannot fire a mid-print change (it would sit at the
// base), so it folds into the base band — unlike bandOf's point rule at emin.
export function baseBand(emin, thresholds) {
  let b = 0;
  for (const t of thresholds) if (t <= emin) b++;
  return b;
}

// Color changes to fire, ascending — for thresholds whose print-Z lands in
// (base, zmax). z = base + (t - emin)·mmPerM·exag; band = i+1. Assumes K>0
// (exag>0; it comes from a 0.5–4 slider). Coincident changes keep the HIGHER
// band; in this module coincidences are exact ties (identical t), so anchoring
// the merge to prev.z is exact.
export function colorChanges(thresholds, frame) {
  const { emin, base, mmPerM, exag, zmax } = frame;
  const K = mmPerM * exag;
  const EPS = 0.05; // mm; merge sub-layer-coincident changes
  const out = [];
  thresholds.forEach((t, i) => {
    const band = i + 1; // crossing threshold i enters band i+1
    const z = base + (t - emin) * K;
    if (z <= base || z >= zmax) return; // at/below base, or above the print
    const prev = out[out.length - 1];
    if (prev && z - prev.z < EPS) { // collapsed onto the previous change:
      prev.band = band;             // keep the higher band (e.g. blue→tundra)
      prev.color = BAND_COLORS[band];
      return;
    }
    out.push({ z, band, color: BAND_COLORS[band] });
  });
  return out;
}

const hex2 = (v) => Math.max(0, Math.min(255, Math.round(v * 255)))
  .toString(16).padStart(2, "0");
const bandHex = (rgb) => `#${hex2(rgb[0])}${hex2(rgb[1])}${hex2(rgb[2])}`;

// PrusaSlicer color-change container (Metadata/Prusa_Slicer_custom_gcode_per_print_z.xml).
// Schema pinned to a real PrusaSlicer-saved project: <custom_gcodes_per_print_z> root
// (no plate wrapper), one <code> per change, type="0" = ColorChange. PrusaSlicer
// re-resolves the actual G-code from printer settings at slice time for type 0, so the
// stored gcode="M600" is a portable placeholder and printer-specific priming is ignored.
export function prusaColorChangeXML(changes) {
  const codes = changes.map((c) =>
    `<code print_z="${c.z.toFixed(3)}" type="0" extruder="1" color="${bandHex(c.color)}" extra="" gcode="M600"/>`
  ).join("");
  return `<?xml version="1.0" encoding="utf-8"?>\n` +
    `<custom_gcodes_per_print_z bed_idx="0">` +
    codes + `<mode value="SingleExtruder"/></custom_gcodes_per_print_z>`;
}

// The base band's color as #RRGGBB — the segment below the first color change
// prints in the starting filament, which prusaFilamentConfig sets so the base
// previews in the band color too.
export function baseColorHex(emin, thresholds) {
  return bandHex(BAND_COLORS[baseBand(emin, thresholds)]);
}

// Minimal PrusaSlicer project config (Metadata/Slic3r_PE.config) setting the
// starting filament colour = the base band, so the base segment (below the first
// M600) previews in the band color instead of the loaded Filament 1. Two things
// are load-bearing, both verified against PrusaSlicer 2.9.6: the "generated by
// PrusaSlicer" header (the identical colour line WITHOUT it is silently ignored
// on Open Project — PrusaSlicer sniffs for it before applying the config), and
// the "; key = value" G-code-comment format (PrusaSlicer's own config
// serialization). extruder_colour is forced empty so filament_colour drives the
// preview; no [Content_Types] entry is needed (PrusaSlicer reads it by path).
export function prusaFilamentConfig(hex) {
  return `; generated by PrusaSlicer 2.9.6 on 2026-07-14 at 22:14:22 UTC\n\n` +
    `; extruder_colour = ""\n; filament_colour = ${hex}\n`;
}
