import { test } from "node:test";
import assert from "node:assert/strict";
import { ThreeMFWriter } from "../js/threeMF.js";

const mesh = { // one degenerate triangle is enough to exercise the writer
  positions: new Float32Array([0, 0, 0, 1, 0, 0, 0, 1, 0]),
  indices: new Uint32Array([0, 1, 2]),
};

// The color-change part name must appear in the zip bytes only when changes given.
const asText = (bytes) => new TextDecoder("latin1").decode(bytes);

test("ThreeMFWriter: no color-change or config part by default", async () => {
  const w = new ThreeMFWriter();
  await w.addObject("t", mesh, 0, 0);
  const text = asText(await w.finish());
  assert.ok(!text.includes("custom_gcode_per_print_z"));
  assert.ok(!text.includes("Slic3r_PE.config"));
});

test("ThreeMFWriter: embeds base filament colour config (with header) when set", async () => {
  const w = new ThreeMFWriter();
  w.setFilamentColor("#295c8c");
  await w.addObject("t", mesh, 0, 0);
  const text = asText(await w.finish());
  assert.ok(text.includes("Metadata/Slic3r_PE.config"));
  assert.ok(text.includes("generated by PrusaSlicer")); // header gates config loading
  assert.ok(text.includes("; filament_colour = #295c8c"));
});

test("ThreeMFWriter: setFilamentColor(null) embeds no config part", async () => {
  const w = new ThreeMFWriter();
  w.setFilamentColor(null);
  await w.addObject("t", mesh, 0, 0);
  assert.ok(!asText(await w.finish()).includes("Slic3r_PE.config"));
});

test("ThreeMFWriter: embeds the color-change part when changes are set", async () => {
  const w = new ThreeMFWriter();
  w.setColorChanges([{ z: 6.4, band: 2, color: [0.6, 0.62, 0.38] }]);
  await w.addObject("t", mesh, 0, 0);
  const bytes = await w.finish();
  const text = asText(bytes);
  assert.ok(text.includes("Prusa_Slicer_custom_gcode_per_print_z.xml"));
  assert.ok(text.includes("custom_gcodes_per_print_z")); // XML root (plural gcodes)
  assert.ok(text.includes('print_z="6.400"'));
});

test("ThreeMFWriter: setColorChanges([]) embeds no part", async () => {
  const w = new ThreeMFWriter();
  w.setColorChanges([]);
  await w.addObject("t", mesh, 0, 0);
  const bytes = await w.finish();
  const text = asText(bytes);
  assert.ok(!text.includes("Prusa_Slicer_custom_gcode_per_print_z.xml"));
  assert.ok(!text.includes("custom_gcodes_per_print_z"));
});
